### ISSUE TITLE
Changing carb ratio doesn't work with every value

### ISSUE THREAD

**Issue by fdotta74** [ivalkou/freeaps#117]
FAX Version: 0.2.1.1
IOS 15.1
Phone: Iphone 12 mini
Emalink

Chosing some values (e.g. 6.1 g/U or 7.8 g/U) CR is automatically reset to 3.0 (see attached movie)

https://user-images.githubusercontent.com/62246679/141456004-2580c815-6dd3-4c91-b4a3-c09922837933.MP4

**Comment by ivalkou** [comment]
Fixed
