### ISSUE TITLE
Add Carbs granularity settings for Apple Watch device

### ISSUE THREAD

**Issue by clvsjr9** [ivalkou/freeaps#137]
Suggestion for new specific Setting menu for Device Watch on iPhone FAX app that offers the opportunity to parameterize the increment/decrement size of the carbohydrate grams to be added or decremented on the watch. Currently, the increase/decrease is only 5g. Parameterized values could offer better customization per diabetic user.

![0g](https://user-images.githubusercontent.com/12844781/144749724-beca56a6-4f88-41e6-9014-e89c9154c627.png)
![5g](https://user-images.githubusercontent.com/12844781/144749727-962309eb-2d61-411d-bbbc-abd982cddb41.png)

**Comment by mountrcg** [comment]
in the meantime you can set the intervall yourself in 
https://github.com/ivalkou/freeaps/blob/03659f5a3ff64c119058690fb5cdae322ba1b965/FreeAPSWatch%20WatchKit%20Extension/Views/CarbsView.swift#L24
and
https://github.com/ivalkou/freeaps/blob/03659f5a3ff64c119058690fb5cdae322ba1b965/FreeAPSWatch%20WatchKit%20Extension/Views/CarbsView.swift#L46

Changed mine to 6.

**Comment by clvsjr9** [comment]
Ops. It's possible to use watch to define the size using scroll. This issue will be closed right now.

**Comment by clvsjr9** [comment]
Function already disposable.

**Comment by mountrcg** [comment]
I am a watch noob @clvsjr9 , how do you use scroll to change the button steps?
