### ISSUE TITLE
Display problem with the Carb factors

### ISSUE THREAD

**Issue by Typ1er** [ivalkou/freeaps#143]
I have a display problem with the carbohydrate factors.

I have set hourly values, language in German.

the display always jumps back to 3g/U when I have set 8.3g/U.
![IMG_6139](https://user-images.githubusercontent.com/39628986/145111486-8fa61c4d-7ba0-4e01-b07f-70b83611de40.PNG)

**Comment by ivalkou** [comment]
fixed https://github.com/ivalkou/freeaps/releases/tag/v0.2.5
