### ISSUE TITLE
HealthKit BG duplication

### ISSUE THREAD

**Issue by mountrcg** [ivalkou/freeaps#145]
I am recording BG values via shortcut in HK after sensor failure during night and warm-up phase.. FreeAPS-X always duplicates the entry after reading eat from HK. Feature or bug?
I deleted all the shortcut entries, but left the last 2 in for viewing:

**Comment by mountrcg** [comment]
![81179A87-FC0E-4A04-BC6C-3FA0CE187396](https://user-images.githubusercontent.com/539276/145531760-fc607108-3632-4d47-89a0-5837b3515893.png)
![484110C8-891D-466F-930F-F8BCB7450861](https://user-images.githubusercontent.com/539276/145531762-c8ac9f77-84c3-499b-94de-2209ad558f51.png)

**Comment by DobbyWanKenoby** [comment]
Please try last dev version. This bug was fixed 2-3 days ago
