### ISSUE TITLE
Feature Request: gauge glucose complication for apple-watch⌚

### ISSUE THREAD

**Issue by iampickle** [ivalkou/freeaps#197]
Hi, a complication in gauge text style would be a nice addition to the apple watch app.
I tried to implement it my self but sadly to inexperienced in swift🥲
[(exsisting project to be build up on)](https://hturan.com/writing/apple-watch-continuous-glucose-monitoring)

**Comment by becksen** [comment]
What is your request would like to have a graph on the watch or that the complication will show the blood glucose value?

**Comment by iampickle** [comment]
> What is your request would like to have a graph on the watch or that the complication will show the blood glucose value?

![image](https://user-images.githubusercontent.com/43931318/177733419-81ba04f8-504d-47ab-ab9e-fb9cd2535f89.png) I'd like a glucose value with directtion arrow to be showen

**Comment by idoodler** [comment]
I'd also love that
