### ISSUE TITLE
Unable to connect to RileyLlink

### ISSUE THREAD

**Issue by idoodler** [ivalkou/freeaps#209]
Hi,
I want to connect my RileyLink to FreeAPS X. I am doing the following:

1. Open the Pump Configuration
2. Tap to add a Metronic-Pump
3. Chose Humalog
4. Switch on the RileyLink
5. It pops up
6. I tap on the switch
7. The RileyLink doesn't light up green and I am unable to go to the next step
    - When I switch it off and on again before tapping on the switch I can continue to the next step, but then the connection fails due to connection loss

According to the RileyLink documentation it should turn green once it is connected to a device, is there a way to debug that?

**Comment by chrisclifford99** [comment]
They can be very monogamous. Did you have the Riley Link connected to
another phone? You might need to forget it on that phone before it will
move over. If not, you may need to reset the Riley Link. I don't recall how
to reset the RL.

Cheers.

**Comment by idoodler** [comment]
Thanks for the quick answer. It was connected to my old phone, but that has been reset and now my spouse is using it. I‘ll research how to reset the RileyLink.Am 19.10.2023 um 22:52 schrieb chrisclifford99 ***@***.***>:﻿
They can be very monogamous. Did you have the Riley Link connected to

another phone? You might need to forget it on that phone before it will

move over. If not, you may need to reset the Riley Link. I don't recall how

to reset the RL.



Cheers.



On Thu, Oct 19, 2023 at 2:50 PM David Gölzhäuser ***@***.***>

wrote:

**Comment by chrisclifford99** [comment]
No problem

I also recalled what to do. If the reset is difficult you may need to
install the loop app on your wife’s phone. Apple remembers a crazy amount
of metadata. You may be able to go in, look at the Riley link and toggle it
off. After that it should pair with your new phone. Once done, delete loop
from your wife’s phone.


Chris

**Comment by idoodler** [comment]
I couldn't make it work I bought an OrangeLink and it is working now

**Comment by eScrappy** [comment]
Just as an FYI, but this code base has been dead / unmaintained for over a year now ... this project was forked to, and renamed as, [iAPS](https://github.com/Artificial-Pancreas/iAPS), where all current development is being done.

The problem with continuing continuing to use this code base is that there are core elements ( like the OrangeLink code ) that are no longer being updated here, but are constantly being updated and improved ... but those patches will never come back to this project, so while bugs are being fixed that may be affecting people here, you will only see work arounds, but never any real fixes.

I heavily recommend to anyone still using FreeAPS X, migrate to the maintained code base, where features are being constantly added, and bugs are constantly being fixed.
