### ISSUE TITLE
Adding Carbs with stale BG's

### ISSUE THREAD

**Issue by mountrcg** [ivalkou/freeaps#28]
Upon entering carbs having a stale BG source FreeAPS keeps waiting/idling at the recommendation screen. One can close that screen and the carbs are added. One could also add a bolus afterwards and even get a recommendation. However if not closing the recommendation screen after entering the carbs it would keep on "turning the wheel".

**Comment by ivalkou** [comment]
Fixed in 6ffa938edd2c6165590b36603d0761ba734f2bcb
