### ISSUE TITLE
Little Visual Detail On Top Line

### ISSUE THREAD

**Issue by clvsjr9** [ivalkou/freeaps#31]
See follow picture:

![IMG_6338](https://user-images.githubusercontent.com/12844781/115119621-c5047a00-9f7f-11eb-8897-223257efc937.jpg)

**Comment by clvsjr9** [comment]
Today with different temp basal values:

![IMG_6344](https://user-images.githubusercontent.com/12844781/115162422-d16cfd80-a079-11eb-91bd-3e1ec9c68237.jpg)

**Comment by ivalkou** [comment]
Fixed 554cef4dcbd8f2cc2958539eb5e09b8a6e8da660
