### ISSUE TITLE
mg/dL unit issues

### ISSUE THREAD

**Issue by naromero77** [ivalkou/freeaps#35]
Even if you choose `mg/dL` under `Glucose units` within `Configuration`-> `Preferences` , `mmol/L` are still used in the follow places:

- Main graph 
- Target Ranges (under `Configuration`)
- Insulin sensitivities (under `Configuration`)

This bug is in the 0.1.6 release.

**Comment by ivalkou** [comment]
@naromero77 Delete then readd goals and insulin sensitivity values and restart the app.
Changing units requires migrating configuration files, which has not yet been implemented.

**Comment by naromero77** [comment]
Thanks that works Ivan.

There is one more place where I still see `mmol/L` units. If you tap on the green circle, `Target`, `minPredBG`, `minGuardBG`, `IOBpredBG`, `COBpredBG`, `UAMprefBG`, and `Eventual BG` are all in `mmol/L`, instead of `mg/dL`.

**Comment by ivalkou** [comment]
fixed in #40
