### ISSUE TITLE
OrangeLink Feature Patch

### ISSUE THREAD

**Issue by clvsjr9** [ivalkou/freeaps#37]
Assess the possibility of incorporating the proposed changes at: https://getrileylink.org/orangelink-loop-patch directly into the FreeAPS X project code, making it easier for the user to compile.

**Comment by mountrcg** [comment]
one issue here I want to point out. If utilizing above mentioned patch OL will work flawlessly. But switching to an EMAlink will result in decreased radio robustness between ema link and omnipod. The frequency will not be be shown on the RileyLink Device page and connection to pod will be lost. Will only reconnect by rebooting iphone.

**Comment by mountrcg** [comment]
> one issue here I want to point out. If utilizing above mentioned patch OL will work flawlessly. But switching to an EMAlink will result in decreased radio robustness between ema link and omnipod. The frequency will not be be shown on the RileyLink Device page and connection to pod will be lost. Will only reconnect by rebooting iphone.

that might have been the same issue that is dicussed between Oct30-Nov01 on Telegram https://t.me/freeapsx_eng/9112

**Comment by ivalkou** [comment]
Done
