### ISSUE TITLE
When No Nightscout as a CGM is present 

### ISSUE THREAD

**Issue by clvsjr9** [ivalkou/freeaps#38]
Recalling the suggestion previously presented for activating the app: xDrip4iO5 when same App Group is being used. Adjust in the openCGM () function and definition as follows:

![ApplicationQueriesSchemes](https://user-images.githubusercontent.com/12844781/115249492-05d6cd00-a0ff-11eb-985b-820752fc4d31.png)

**Comment by Jon-b-m** [comment]
clvsjr9 does this work for you? It doesn't for me...

**Comment by clvsjr9** [comment]
@Jon-b-m, it worked by making the following adjustments. I'm not sure if these are the best options:

Use Local local glucose server: ON and this little program modification on openCGM function:

![openCGM](https://user-images.githubusercontent.com/12844781/115969253-73756580-a512-11eb-99a0-429f0db31ccb.png)

and this URLschemes addition on xdripswift project:

![URLschemes](https://user-images.githubusercontent.com/12844781/115969316-b20b2000-a512-11eb-809a-a1e2830390a8.png)

**Comment by clvsjr9** [comment]
To facilitate future use: #https://github.com/JohanDegraeve/xdripswift/issues/220

**Comment by paulplant** [comment]
> To facilitate future use: #[JohanDegraeve/xdripswift#220](https://github.com/JohanDegraeve/xdripswift/issues/220)

PR done to implement this into xdripswift develop branch. It will be merged into master over the weekend.

https://github.com/JohanDegraeve/xdripswift/pull/231

**Comment by clvsjr9** [comment]
Any visual indicator can be interesting to indicate that App Group is OK. Something like a successful link between apps for example.

**Comment by clvsjr9** [comment]
Examining a Message Port described at: https://developer.apple.com/documentation/corefoundation/cfmessageport-rs2 can be interesting to test FAX AppGroup option of CGM configuration/communication on the local phone with others apps.

**Comment by ivalkou** [comment]
done
