### ISSUE TITLE
TempBasal during Omnipod change

### ISSUE THREAD

**Issue by mountrcg** [ivalkou/freeaps#49]
on 0.1.19 I noticed that the tempbasal scheduled to run during the pod change will run to its end, even after the screaming starts.

![5C6BCAFC-6C0A-486A-AEE8-C0DF1A9B96EA](https://user-images.githubusercontent.com/539276/115948645-a0ecef80-a4cf-11eb-9f23-dab2c27b1bba.jpeg)
![0869CBFE-AC39-42D8-9BAA-FE0E75A75F80](https://user-images.githubusercontent.com/539276/115948648-a34f4980-a4cf-11eb-8d88-ba74ea5b8cce.jpeg)

**Comment by mountrcg** [comment]
This is how it looks retrospectively. I realy took the 80mins to change the pump

**Comment by mountrcg** [comment]
![Uploading 38440418-95F9-4288-BA30-11BB1093C046.jpeg…]()

**Comment by mountrcg** [comment]
![EB3E8727-E798-48B5-9FC1-6DBA3DF682E0](https://user-images.githubusercontent.com/539276/115958072-17a4df80-a506-11eb-8f6a-448b249f12e6.jpeg)

**Comment by bjornoleh** [comment]
Not sure about the relevance, but also in Loop there is an issue with IOB counts during pod change. The recommended procedure for Loop (according to  @marionbarker, and I have followed this advice too) is to suspend the old pod before deactivating it. Then Loop will know that the insulin delivery has stopped. 

Perhaps it is a good idea to do the same thing in FreeAPS X? At least until a proper solution is available?

Details for Loop here, although this may be irrelevant in the context of FreeAPS X:
https://github.com/LoopKit/Loop/issues/1271

**Comment by ivalkou** [comment]
@mountrcg This is not a bug. TRB will be drawn on the chart as indicated in the last history entry. This is why I make the pump suspend opaque. You yourself have changed the appearance of the chart.

**Comment by mountrcg** [comment]
@ivalkou my concern was not the graph, but the accounting of basal insulin during pod change, I did make that clear above - sorry.
