### ISSUE TITLE
Feature Request: OpenAPS Advanced Meal Assist (AMA)

### ISSUE THREAD

**Issue by naromero77** [ivalkou/freeaps#51]
I am not sure if this is implemented already, but it would be a could stepping stone for those who are using oref0 and a preparing to move to oref1.
https://newer-docs.readthedocs.io/en/latest/docs/walkthrough/phase-4/advanced-features.html#advanced-meal-assist-or-ama

https://androidaps.readthedocs.io/en/latest/Usage/Open-APS-features.html#advanced-meal-assist-ama

Again, perhaps this is implemented already as is now just considered part of the main oref0.

**Comment by ivalkou** [comment]
AMA is part of oref0
