### ISSUE TITLE
Feature request: show carbs required in info panel and/or in future widget

### ISSUE THREAD

**Issue by Jon-b-m** [ivalkou/freeaps#57]
Currently you can see carbs required in the suggestion box, but it would also be useful to have it show in the info panel (for instance) and / or in a widget. To have it pushed as a notification also would be a big plus.

**Comment by WKaufman** [comment]
I agree. This would be a great feature.

**Comment by jchenley** [comment]
> I agree. This would be a great feature.

I was hoping for the exact same feature

**Comment by ivalkou** [comment]
Done 5dc0b07c3a009d94bbd61fea436cd76fe3836c4d
