### ISSUE TITLE
 IOB curve isn't displayed correctly in NS day to day reports

### ISSUE THREAD

**Issue by bjornoleh** [ivalkou/freeaps#59]
The IOB curve isn't displayed correctly in NS day to day reports.

Version 0.1.23 RC

![20210514_082109](https://user-images.githubusercontent.com/63544115/118318983-68529b80-b4fa-11eb-832e-0cccbb853ff0.jpg)

The transition from Loop to FreeAPS X is at around 16.00 on the 12th. It is marked by a profile switch.

With Loop, the IOB trace is as expected. With FAPSX there is nothing the first hours, then next day just a gradually increasing linear slope.

I have disabled display of basal and COB here to make IOB more prominent.

IOB from FAPSX is displayed correctly in the main view of Nightscout.

It is correctly displayed in reports for AAPS users, so not an issue with oref.

**Comment by bjornoleh** [comment]
There is something strange with the COB trace as well, at least fir the day in the middle in the screenshot below. This could be unrelated to the IOB issue, I don't know. 

![Screenshot_20210517-000127_Chrome](https://user-images.githubusercontent.com/63544115/118414188-7a237280-b6a3-11eb-83ff-8b1993bb4741.jpg)

**Comment by marionbarker** [comment]
I think the problem is that IOB is not reported in the OpenAPS pill - only found in the IOB pill.  
The COB is reported in the OpenAPS pill which is why it can be shown in plots.
![Marion-20210611-0821](https://user-images.githubusercontent.com/19607791/121710251-46631f00-ca8e-11eb-97d2-a7716dc43b73.png)

**Comment by bjornoleh** [comment]
@marionbarker, thanks, that is possible. I have AAPS running in simulation on my phone, connected to a backup NS instance. IOB is reported there, so clearly a difference compared to FAPSX.

**Comment by bjornoleh** [comment]
![Screenshot_20210612-202333_Chrome](https://user-images.githubusercontent.com/63544115/121785887-c38cb200-cbbc-11eb-98c1-db9e2016dc43.jpg)

**Comment by bjornoleh** [comment]
I was wondering if OpenAPS also display  IOB in the openaps pill. According to screenshots in this issue, that seems to be the case. 

https://github.com/openaps/oref0/issues/1405

![PNG-bilde](https://user-images.githubusercontent.com/63544115/146274487-93d9a7e4-26a8-4ec7-b0b8-f4ba89ece803.png)

So it seems FAX is displaying less info in the openaps pill than OpenAPS and AAPS. And this appears to be the cause of the missing IOB trace in the NS Day to day reports. 

Would it be possible to add IOB to what is reported in the openaps pill?

**Comment by bjornoleh** [comment]
For reference, FreeAPS dev v0.2.4 does not display IOB:

![Skjermbilde 2021–12–15 kl  23 31 33](https://user-images.githubusercontent.com/63544115/146275477-a3695862-73bf-4581-ad6e-ba7095c2f54d.png

It’s not too important to have the IOB value displayed in the pill, but getting the NS reports to work as intended is, as it give valuable information when adjusting settings.

**Comment by marionbarker** [comment]
I sent Ben West a PM about this when I was using FAX and he thought it was a FAX problem.
But then I talked to someone who uses AAPS and she said the IOB doesn't plot in day-to-day reports for her.

The concept of plotting IOB and COB to help in adjusting settings is used a lot in Loop, where the plots work.
There are some graphics features available with OpenAPS in Day-to-Day reports that do not work in Loop.

I modified my Omnipod message parser to handle FAX log files and added an IOB, COB, etc plot, but that requires saving the log files daily and running a python parser (on a mac).

**Comment by bjornoleh** [comment]
I think I have checked this before, at least I checked now by firing up my Android phone with AAPS in sim mode. AAPS do show the IOB trace, as long as the IOB checkbox is ticked. See from around 19:00 below:

![5 7 -0 5 →](https://user-images.githubusercontent.com/63544115/146443036-43e29c0b-15d6-45d9-9226-6e64de9a2cb1.png)

**Comment by bjornoleh** [comment]
https://github.com/ivalkou/freeaps/commit/0f8de8274303ec65169ace4f008448168a6a814d fixed this bug.Thanks!
