### ISSUE TITLE
Decimal error when editing entry

### ISSUE THREAD

**Issue by marionbarker** [ivalkou/freeaps#62]
When editing a bolus entry, deleting the number following decimal point also deletes the decimal. 

Example: initial entry
1.6
But desired entry is 1.2 u. 

If you tap delete then 2, entry is 12 because both the 6 and decimal point are deleted with a single tap of delete key.

**Comment by marionbarker** [comment]
This also happens for other decimal entries, e.g., autosens max.

**Comment by ivalkou** [comment]
fixed https://github.com/ivalkou/freeaps/releases/tag/v0.2.5
