### ISSUE TITLE
Split "Initial" by "Advanced" preferences and add config descriptions 

### ISSUE THREAD

**Issue by FlorinBv** [ivalkou/freeaps#70]
Especially for who is starting with FreeAPS X, it would be great to split the [Initial ](https://www.loopandlearn.org/freeaps-x/#pref-0)by [Advanced ](https://www.loopandlearn.org/freeaps-x/#pref-1)preferences, as described in [LoopAndLearn ](https://www.loopandlearn.org/freeaps-x/)

In addition, it would be great to add an "i" info icon for each setting with short description and default/recommended value. This is not to replace the wiki, but it would be a great quick reminder in case the settings are reviewed after a while. 

I have added a short video on youtube with menu and description from Loop Dev (tidepool merged version) which I consider very useful and might be an inspiration for FreeAPS X too 
[https://youtu.be/efZ8aUz9_i0](https://youtu.be/efZ8aUz9_i0 )

**Comment by Jon-b-m** [comment]
Sounds complicated, there are so many settings already, and splitting them in more views or sections would make the preferences less coherent and more difficult to overview. And who decides what is advanced or not? The user of the app or Ivan 😜the Great? There already are default values when you start. Making the defaults more obvious would be good, but that can be included in the descriptions.

**Comment by ivalkou** [comment]
Done
