### ISSUE TITLE
ISSUE: Unusual expiration reminder date for pod when changing pod early

### ISSUE THREAD

**Issue by straykatz** [ivalkou/freeaps#71]
Hi, I just changed a pod early, after about 2 days and some hours. 

After priming, in the screen with the expiration reminder, the pre-filled Expiration Reminder looks to have carried over the value from the previous pod ("tomorrow at 10:16"). That should probably update to a time closer to 3 days, probably in line with what's shown on the selector below. 
See photo. 

![image](https://user-images.githubusercontent.com/45725845/121274074-8b186b80-c87e-11eb-841a-c58ce9fff1da.jpeg)

The selector shows a expiration reminder 48 hours from pod activation (June 10, 16:42).

**Comment by marionbarker** [comment]
This is a riley_ios problem that happened with a recent UI change that wasn't tested well enough (with Loop v2.2.4).  Not anything Ivan should be dealing with. Here's the work around.

https://loopkit.github.io/loopdocs/operation/loop-settings/pump-commands/#expiration-reminder

**Comment by straykatz** [comment]
Ah, cool, Thank you, Marion. I'll close the issue.
