### ISSUE TITLE
FreeAPS X and IOS 15.x ( latest public beta )

### ISSUE THREAD

**Issue by scrappy** [ivalkou/freeaps#80]
Not sure how to provide information on this, but at present ( latest public beta of IOS 15.x ), the app starts up and looks fine, but if you go into Settings, other then flipping 'Closed Loop' off / on, none of the submenus do anything ...

I loaded the exact same build onto a separate 14.x iPhone, and it works as expected.

I am planning on switching to FreeAPS X on Saturday ( next pump ) using my old phone, but Loop *is* working fine on 15.x, including the setup sub-menus.

Happy to provide more information if folks want to tell me how ... ?  Willing to do a zoom / screen share with someone                who knows what they are doing to gather more info also ...

**Comment by scrappy** [comment]
I've just retested this with the new Beta4 that just came out ... its gotten even worse, am no longer able to even get *into* settings, where at least before I could get into settings, just not into the lower menus.

General Release for 15.x is predicted to be Early Fall ... looking at the last 3 major version releases, they all seemed to happen around the 19th of September ... if they do same for 15.x, that is in ~7 weeks ... anything I can do to help debug, am happy to do ...

**Comment by birdfly** [comment]
The same for me ,I have two iPhone running newest iOS15 beta

**Comment by birdfly** [comment]
The same for me ,I have two iPhone running newest iOS15 beta

**Comment by hansdampf01** [comment]
Same goes for the RC

**Comment by ivalkou** [comment]
Fixed in dev branch
