### ISSUE TITLE
Feature request: Add capillary BG, for instance when sensor is warming up/not reading, or enable fetch of manually added BG in NS.

### ISSUE THREAD

**Issue by Jon-b-m** [ivalkou/freeaps#91]
This would be useful when sensor is not working as blood glucose source, in order to always keep looping

**Comment by dcheslow** [comment]
+1 I wished for this feature just this morning when my sensor stopped and I have not yet received a new box.

**Comment by Jon-b-m** [comment]
> +1 I wished for this feature just this morning when my sensor stopped and I have not yet received a new box.

You can use this app for adding capillary BG readings to FreeAPS X and to NS. It's a really great CGM app for European Libre 2 sensors also. https://github.com/creepymonster/LibreDirectApp

**Comment by ivalkou** [comment]
Implemented as Health Kit integration
